### ISSUE TITLE
Title: AtD: access-the-data

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/admin-project-board-migration#2]
### Overview
We need to migrate the GitHub project boards on this repo so that we don't lose any content.

#### Details
Content includes
- Cards (The new project boards don't support cards)
- Merging multiple boards into one board with different views
- capturing closed boards

#### Evaluate
- [x] Add strike-through to actions * that do not need to be taken in this section (see Resource 1.03 for more detail)
   - Cards to copy *
   - Multiple Boards Migration *
   - ~Single Board Migration~ *
   - Issues not on board *
- [x] Add the labels for all the actions that need to be completed
- [x] Remove the `evaluate` label and add the `prepare` label

#### Prepare
Do the following actions unless strike though indicated above by going to the wiki (1.06) and following the instructions
- [x] Cards to copy
- [x] Remove the `prepare` label and add the `migrate` label

#### Migrate
Do the following actions unless strike though indicated above by going to the wiki (1.06) and following the instructions
- [x] Boards Migration
   - [x] Multiple Boards Migration
   - [ ] Single Board Migration
- [x] Remove the `migrate` label and add the `cleanup` label

#### Cleanup
Do the following actions by going to the wiki (1.06) and following the instructions
   - [x] Issues not on board
   - [x] Customize (optional)
   - [ ] Close out Migration

#### Resources for creating this issue
- 1.01 Project Initials: AtD
- 1.02 Repo: https://github.com/hackforla/access-the-data
- 1.03 Classic Project Board(s) open:
   - [V2: Data Catalog Tutorials](https://github.com/hackforla/access-the-data/projects/9)
   - [V1: Data Catalog](https://github.com/hackforla/access-the-data/projects/8)
   - [MVP - CLOSED](https://github.com/hackforla/access-the-data/projects/6)
   - [ATD Product Management](https://github.com/hackforla/access-the-data/projects/1)
- 1.04 Classic Project Board(s) closed:
   - [[ON HOLD] AtD Personas](https://github.com/hackforla/access-the-data/projects/7)
   - [AtD Data Catalog](https://github.com/hackforla/access-the-data/projects/5) 
   - [[ON HOLD] AtD Educational Module](https://github.com/hackforla/access-the-data/projects/4)
- 1.05 New Project Board: [Name] 
- 1.06 Actions wiki: https://github.com/hackforla/admin-project-board-migration/wiki

#### Resources created while working on this issue
- 2.01 Migration Issue: https://github.com/hackforla/access-the-data/issues/305
- 2.02 New Project Board:  [Name]

**Comment by ExperimentsInHonesty** [comment]
I created labels that matched the project board views https://github.com/hackforla/access-the-data/labels?q=PBV%3A and then migrated all the issues to the new board  https://github.com/orgs/hackforla/projects/124

**Comment by Rabia2219** [comment]
#### Notes

- updated the wiki
  - replaced all old project board links with new ones
  - revised old recruitment method
  - revised the AtD GitHub board description and image
