### ISSUE TITLE
311 Data: 311-data

### ISSUE THREAD

**Issue by Rabia2219** [hackforla/admin-project-board-migration#44]
### Overview
We need to migrate the GitHub project boards on this repo so that we don't lose any content.

#### Details
Content includes
- Cards (The new project boards don't support cards)
- Merging multiple boards into one board with different views
- capturing closed boards

#### Evaluate
- [x] Add strike-through to actions * that do not need to be taken in this section (see Resource 1.06 for more detail)
   - Cards to copy *
   - Multiple Boards Migration *
   - ~Single Board Migration~ *
   - Issues not on board *
- [x] Add the labels for all the actions that need to be completed
- [x] Remove the `evaluate` label
- [x] Add the next label
   - [ ] If the Cards to copy has been strike-through, add the `migrate` label and check off/skip the Prepare section 
   - [x] If the Cards to copy has not been strike-through, add the `prepare` label 

#### Prepare
Do the following actions unless strike though indicated above by going to the wiki (1.06) and following the instructions
- [x] Cards to copy
- [x] Remove the `prepare` label and add the `migrate` label

#### Migrate
Do the following actions unless strike though indicated above by going to the wiki (1.06) and following the instructions
- [x] Boards Migration
   - [x] Multiple Boards Migration
   - [ ] Single Board Migration
- [x] Remove the `migrate` label and add the `cleanup` label

#### Cleanup
Do the following actions by going to the wiki (1.06) and following the instructions
   - [x] Issues not on board
   - [x] Customize (optional)
   - [ ] Close out Migration https://github.com/hackforla/311-data/issues/1797

#### Resources for creating this issue
- Project Initials: 311 Data
- 1.02 Repo: https://github.com/hackforla/311-data
- 1.03 Classic Project Board(s) open:
   - [20200414 - NC Workshop Board](https://github.com/hackforla/311-data/projects/6) * migrated and deleted
- 1.04 Classic Project Board(s) closed:
   - [311: project board](https://github.com/hackforla/311-data/projects/10)* migrated and deleted
   - [Vision Board](https://github.com/hackforla/311-data/projects/8)* deleted
   - [Data Analysis Projects](https://github.com/hackforla/311-data/projects/7) * deleted
   - [311 MVP](https://github.com/hackforla/311-data/projects/4)* moved issues to new board, added the v1 label, and deleted
   - [MVP](https://github.com/hackforla/311-data/projects/3)* deleted
   - [Project Management](https://github.com/hackforla/311-data/projects/2)* deleted
- 1.05 New Project Board: [311: Project Board](https://github.com/orgs/hackforla/projects/63)
- 1.06 Actions wiki: https://github.com/hackforla/admin-project-board-migration/wiki

#### Resources created while working on this issue
- 2.01 Migration Issue: https://github.com/hackforla/311-data/issues/1797
- 2.02 New Project Board:  [Name]
- Card Content Spreadsheets*
   - [Project Board Cards: 311-data: 20200414 - NC Workshop Board](https://docs.google.com/spreadsheets/d/1xtNLwofLwpsQn-ZsWwbNQxsQYcGF-z_PiO5x3EQmsbM/edit)

**Comment by Rabia2219** [comment]
#### Notes

- cards copied, issues moved, boards deleted
- views created on new board
- access permissions to new board updated

**Comment by ExperimentsInHonesty** [comment]
card migration issue on repo closed out
